language: rust
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo build --features "openssl irc"
  - cargo test --features "openssl irc"
notifications:
  irc:
    channels:
      - "irc.fyrechat.net#vana-commits"
    template:
      - "%{repository_slug}/%{branch} (%{commit} - %{author}): %{message}"
    skip_join: true
