language: rust
sudo: false
script:
  - cargo build --verbose
  - cargo test --verbose
  - cargo build --features all
  - cargo test --features all
notifications:
  email: false
  irc:
    channels:
      - "irc.fyrechat.net#vana-commits"
    template:
      - "%{repository_slug}/%{branch} (%{commit} - %{author}): %{message}"
    skip_join: true
